export const listOfSovereignStates = ['', 'United States', 'Afghanistan', ' Åland Islands', ' Albania', ' Algeria', ' American Samoa', ' Andorra', ' Angola', ' Anguilla', ' Antarctica', ' Antigua and Barbuda', ' Argentina', ' Armenia', ' Aruba', ' Australia', ' Austria', ' Azerbaijan', ' Bahamas', ' Bahrain', ' Bangladesh', ' Barbados', ' Belarus', ' Belgium', ' Belize', ' Benin', ' Bermuda', ' Bhutan', ' Bolivia (Plurinational State of)', ' Bonaire', ' Sint Eustatius and Saba', ' Bosnia and Herzegovina', ' Botswana', ' Bouvet Island', ' Brazil', ' British Indian Ocean Territory', ' British Virgin Islands', ' Brunei Darussalam', ' Bulgaria', ' Burkina Faso', ' Burundi', ' Cabo Verde', ' Cambodia', ' Cameroon', ' Canada', ' Cayman Islands', ' Central African Republic', ' Chad', ' Chile', ' China', ' China', ' Hong Kong Special Administrative Region', ' China', ' Macao Special Administrative Region', ' Christmas Island', ' Cocos (Keeling) Islands', ' Colombia', ' Comoros', ' Congo', ' Cook Islands', ' Costa Rica', ' Côte d’Ivoire', ' Croatia', ' Cuba', ' Curaçao', ' Cyprus', ' Czechia', ' Democratic Peoples Republic of Korea', ' Democratic Republic of the Congo', ' Denmark', ' Djibouti', "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia (Federated States of)", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "North Macedonia", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Republic of Korea", "Republic of Moldova", "Réunion", "Romania", "Russian Federation", "Rwanda", "Saint Barthélemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin (French Part)", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Sark", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten (Dutch part)", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Sweden", "Switzerland", "Syria", "Tajikistan", "Taiwan", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Türkiye", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom of Great Britain and Northern Ireland", "United Republic of Tanzania", "United States Minor Outlying Islands", "United States Virgin Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela (Bolivarian Republic of)", "Vietnam", "Wallis and Futuna Islands", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"];
export const tvRatings= ["", "13+", "16+", "18+", "7+", "ALL", "NR", "PG", "R", "TV-14", "TV-G", "TV-MA", "TV-NR", "TV-PG", "TV-Y", "TV-Y7", "TV-Y7-FV"];
export const movieRatings = ["", "G", "NC-17", "NR", "PG", "PG-13", "R", "TV-14", "TV-G", "TV-MA", "TV-PG", "TV-Y", "TV-Y7", "UR"];
export const tvGenres = ["", "Action",  "Action & Adventure", "Action-Adventure", "Adult Animation", "Adventure", "Animals & Nature", "Animation", "Anime", "Anime Features", "Anime Series", "Anthology", "Arthouse", "Arts", "Biographical", "Black Stories", "British TV Shows", "Buddy", "Cartoons", "Children & Family Movies", "Classic & Cult TV", "Classic Movies", "Classics", "Comedies", "Comedy", "Coming of Age", "Concert Film", "Cooking & Food", "Crime", "Crime TV Shows", "Cult Movies", "Dance", "Disaster", "Documentaries", "Documentary", "Docuseries", "Drama", "Dramas", "Entertainment", "Faith & Spirituality", "Faith and Spirituality", "Family", "Fantasy", "Fitness", "Game Show / Competition", "Game Shows", "Health & Wellness", "Historical", "History", "Horror", "Horror Movies", "Independent Movies", "International", "International Movies", "International TV Shows", "Kids", "Kids' TV", "Korean TV Shows", "Late Night", "Latino", "LGBTQ", "LGBTQ Movies", "LGBTQ+", "Lifestyle", "Lifestyle & Culture", "Medical", "Military and War", "Movies", "Music", "Music & Musicals", "Music Videos and Concerts", "Musical", "Mystery", "News", "Parody", "Police/Cop", "Reality", "Reality TV", "Romance", "Romantic Comedy", "Romantic Movies", "Romantic TV Shows", "Sci-Fi & Fantasy", "Science & Nature TV", "Science & Technology", "Science Fiction", "Series", "Sitcom", "Sketch Comedy", "Soap Opera / Melodrama", "Spanish-Language TV Shows", "Special Interest", "Sports", "Sports Movies", "Spy/Espionage", "Stand Up", "Stand-Up Comedy", "Stand-Up Comedy & Talk Shows", "Superhero", "Survival", "Suspense", "Talk Show", "Talk Show and Variety", "Teen", "Teen TV Shows", "Thriller", "Thrillers", "Travel", "TV Action & Adventure", "TV Comedies", "TV Dramas", "TV Horror", "TV Mysteries", "TV Sci-Fi & Fantasy", "TV Shows", "TV Thrillers", "Unscripted", "Variety", "Western", "Young Adult Audience"];
export const movieGenres = ["", "Action", "Adventure", "Animation", "Comedy", "Crime", "Documentary", "Drama", "Family", "Fantasy", "Foreign", "History", "Horror", "Music", "Mystery", "Romance", "Science Fiction", "Thriller", "TV Movie", "War", "Western"];
export const codes = {" All Languages": "",
  "Abkhazian": "ab",
"Afrikaans": "af",
"Amharic": "am",
"Arabic": "ar",
"Aymara": "ay",
"Bulgarian": "bg",
"Bambara": "bm",
"Bengali": "bn",
"Tibetan": "bo",
"Bosnian": "bs",
"Catalan": "ca",
"Chinese": "cn",
"Czech": "cs",
"Welsh": "cy",
"Danish": "da",
"German": "de",
"Greek": "el",
"English": "en",
"Esperanto": "eo",
"Spanish": "es",
"Estonian": "et",
"Basque": "eu",
"Persian": "fa",
"Finnish": "fi",
"French": "fr",
"Frisian": "fy",
"Galician": "gl",
"Hebrew": "he",
"Hindi": "hi",
"Croatian": "hr",
"Hungarian": "hu",
"Armenian": "hy",
"Indonesian": "id",
"Icelandic": "is",
"Italian": "it",
"Inuktitut": "iu",
"Japanese": "ja",
"Javanese": "jv",
"Georgian": "ka",
"Kazakh": "kk",
"Kannada": "kn",
"Korean": "ko",
"Kurdish": "ku",
"Kyrgyz": "ky",
"Latin": "la",
"Luxembourgish": "lb",
"Lao": "lo",
"Lithuanian": "lt",
"Latvian": "lv",
"Macedonian": "mk",
"Malayalam": "ml",
"Mongolian": "mn",
"Marathi": "mr",
"Malay": "ms",
"Maltese": "mt",
"Norwegian Bokmål": "nb",
"Nepali": "ne",
"Dutch": "nl",
"Norwegian": "no",
"Punjabi": "pa",
"Polish": "pl",
"Pashto": "ps",
"Portuguese": "pt",
"Quechua": "qu",
"Romanian": "ro",
"Russian": "ru",
"Kinyarwanda": "rw",
"Serbo-Croatian": "sh",
"Sinhala": "si",
"Slovak": "sk",
"Slovenian": "sl",
"Samoan": "sm",
"Albanian": "sq",
"Serbian": "sr",
"Swedish": "sv",
"Tamil": "ta",
"Telugu": "te",
"Tajik": "tg",
"Thai": "th",
"Tagalog": "tl",
"Turkish": "tr",
"Ukrainian": "uk",
"Urdu": "ur",
"Uzbek": "uz",
"Vietnamese": "vi",
"Wolof": "wo",
"Unknown": "xx",
"Mandarin": "zh",
"Zulu": "zu"};
// Function for displaying services offering a given show 
export function commaSeparated(arr) {
  const preprocess = arr.map(obj=>obj.provider);
  return preprocess.join(", ");
}